### ISSUE TITLE
Options window scaling

### ISSUE THREAD

**Issue by Geexp** [cmdwtf/KeePassDiceware#12]
The Diceware settings window doesn't scale properly on my machine. 

Resolution is 3860x2400 with 200% scaling.

Can this be fixed through Windows / Keepass settings or does the plugin need updating? 

![image](https://user-images.githubusercontent.com/107115325/172603525-747f753e-a56b-477b-8a75-59469917956d.png)
 
Thank you.

**Comment by nitz** [comment]
That's a fantastic question. I know how to [handle high dpi](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8) from the application side, but I'm not quite sure what needs to be done to let a window created from a library/plugin. It may be as simple as something like this:

```diff
diff --git a/DicewareOptionsForm.Designer.cs b/DicewareOptionsForm.Designer.cs
index 5e2ccc0..f1b7867 100644
--- a/DicewareOptionsForm.Designer.cs
+++ b/DicewareOptionsForm.Designer.cs
@@ -290,6 +290,8 @@ namespace KeePassDiceware
 			// DicewareOptionsForm
 			// 
 			this.AcceptButton = this.okButton;
+			this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
+			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
 			this.CancelButton = this.cancelButton;
 			this.ClientSize = new System.Drawing.Size(493, 709);
 			this.Controls.Add(this.ExplanationGroupBox);
```

The default value is to 'inherit', but I wonder if that inheritance doesn't cross over from the original appdomain.

I've built a version with this change if you'd like to try it:

[KeePassDiceware-with-dpi-aware-change.zip](https://github.com/cmdwtf/KeePassDiceware/files/8861288/KeePassDiceware-with-dpi-aware-change.zip)

**Comment by Geexp** [comment]
Super quick response, thanks Chris!

Just tried the new version and it has worked -  hurrah. Thank you! 

![image](https://user-images.githubusercontent.com/107115325/172635916-48cf6e7e-d8be-46ab-a811-cde0436b7bb3.png)

Appreciate your work on the plugin - I was reluctant to use KP to generate passwords until I started using your plugin.

**Comment by nitz** [comment]
Awesome! I'm glad it worked, that was a complete shot in the dark 😂

And I'm glad -- Ever since I used @strongbox-password-safe's app to generate a password (which is where I got the general design/wordlists for this plugin), I knew I wanted that everywhere!

I'll get these changes committed so they'll be in the next actual release, but you should be fine to keep using that build!
