### ISSUE TITLE
Error when opening with KeePassDiceware

### ISSUE THREAD

**Issue by avoca999** [cmdwtf/KeePassDiceware#13]
I'm getting the attached error when opening KeePass with the latest DLL (downloaded today). Since nobody else has logged it, maybe there's something wrong with my setup!
![Screenshot (308)](https://user-images.githubusercontent.com/32246338/182136301-221a7f85-3eb9-4159-8acb-54833f783716.png)

**Comment by nitz** [comment]
Hm, what version of KeePass are you using? Is it at least `v2.51.1`?

Also, do you have the .NET Framework `v.4.5.2` (at least) installed?

You should be able to see what version is installed by running this command from a command prompt:

`reg query "HKLM\SOFTWARE\Microsoft\Net Framework Setup\NDP\v4\Full" /V Version`

**Comment by avoca999** [comment]
FANTASTIC, thank you! I thought I was on the latest KeePass, but I was on the previous one. All working fine now!
