### ISSUE TITLE
Smaller (e.g. laptop) screens cannot use the config dialog

### ISSUE THREAD

**Issue by me-and** [cmdwtf/KeePassDiceware#17]
On one of my laptops, with a 1920x1080 resolution and 150% scale set (as recommended) in Windows 11, the "Diceware Password Genaration Options" window looks like the below:

![image](https://user-images.githubusercontent.com/1397507/206403075-72d2b4e5-a5e9-40b3-89ed-a2b559189e0d.png)

There's a scrollbar down the side, but it only gets me as far as the XKCD link. There's no way to access the "OK" and "Cancel" buttons at the bottom of the dialog.

Right now this is fine: I'm using a dock, and if I move the KeePass "Password Generator" dialog to one of my larger monitors before I click the cog icon to open the Diceware dialog, it opens large enough for the buttons to be visible. But I suspect if I were using the laptop undocked, I'd need to go into Windows' settings and twiddle the resolution or scaling before I could actually make any changes.

**Comment by nitz** [comment]
Interesting! I wonder how it's made it's mind up to definitely pay attention that it needs to scale, but then scale wrong.

As another temporary workaround: if you use <kbd>Tab</kbd> to cycle through controls, does it get you to the OK/Cancel?

Also, your scrollbars look like they're Windows 11, yeah? Could you snag me your build number and feature version? (<kbd>Win</kbd>+<kbd>R</kbd>, `winver`, `OK`) I can't seem to replicate it on my Windows 10 machine so I'm wondering if it's got something to do with the newer explorer UI bits.

**Comment by me-and** [comment]
Ah, a detail I should have added: the vertical height of that window on that screen is the entire vertical height from the top of the monitor to the top of the taskbar. I suspect what's going wrong is when the window is created, the window size is being constrained by the available space on that monitor.

[Here's a log from Steps Recorder showing reproducing the problem and tabbing through the elements](https://github.com/cmdwtf/KeePassDiceware/files/10193558/KeePass.Diceware.UI.problem.steps.zip). You _should_ be able to open the log using most browsers, but let me know if that's not the case. What that shows – and which wasn't visible without the highlighting Steps Recorder adds – is that the reason the scroll bar doesn't let you scroll down to the OK/Cancel buttons is that they're positioned _behind_ the "Explanation" UI element group.

I suspect that means the correct fix is to (a) fix whatever's causing the buttons to appear behind the Explanation group such that they're correctly stacked on top of each other, and (b) to make the window resizable.

I think that's a better fix than, say, forcing the window to spawn with a minimum size, because that'd make interacting with it on small screens even more difficult (you'd need to move the top of the window off the top of the screen), and it also means that you wouldn't be able to move the window onto a higher-resolution desktop then resize it to use the full window properly.

FWIW, I originally saw this on a machine running Windows 11 Enterprise 22H2 build 22623.1028, but I've just reproduced the same problem using a VM running Windows 10 Pro N 22H2 build 19045.2311. The key thing seems to be getting the display small enough that the full size window doesn't fit.

**Comment by nitz** [comment]
Hey Adam, give v1.4.1 a shot.

I tinkered around with a number of different ways, but any time I let Windows try to handle the sizing it always ended up creating the same issue. It's something to do with the control anchoring and the way "bottom right" works with DPI scaling. My "fix" was to stick the contents of the window on a particularly sized panel that was exactly large enough for the window, which *does* scale properly when the DPI settings hit it, the scrollbars that generate on the window scroll just that panel instead, which should let all the controls be visible.

Let me know if you run into any oddities!

**Comment by me-and** [comment]
@nitz Yes, that works, thank you! Everything's visible (or at least scrollable-to-be-visible) however I open the dialog, and everything works as expected even when moving an already-opened dialog between monitors with different scale settings.

The only slight oddity is that, when opening the dialog on a small monitor, it's created with the scrollbar most of the way to the bottom, so elements at the top of the dialog aren't visible. I'd have expected the window to start scrolled to the top. I suspect that's because it's starting with the OK button having focus, and it wants to make sure the element that has focus is visible.

That's very minor, though! I'm happy to raise a new issue for that if you'd like, but it's certainly not something I'd be bothered about. I just figured I'd note it while I was checking things over :)
