### ISSUE TITLE
Error when installing plug-in

### ISSUE THREAD

**Issue by Hexamailman** [cmdwtf/KeePassDiceware#20]
Hello,

When I put the DLL in KeePass directory, there is an error when I start KeePass.
![image](https://user-images.githubusercontent.com/102728999/221183294-270e49cb-7541-4871-948b-c646d4dd606f.png)

Do you have an idea how I can resolve this error ?

KeePass version is 2.43 on Windows 10.

Thanks !
Best regards.

**Comment by Hexamailman** [comment]
Sorry, I just realized my KeePass version was too old. It works with version 2.53. I close the issue.

**Comment by nitz** [comment]
Hey @Hexamailman! I'm glad you got it worked out. I'll make sure to add a note about this in the readme, as I'm sure you're not the only one who may run into this!

Cheers
