### ISSUE TITLE
Switching between two saved configurations do not update settings

### ISSUE THREAD

**Issue by Truncated** [cmdwtf/KeePassDiceware#3]
Using Keepass 2.50 64-bit. Used Password Generator to make two Profiles.

- One has 4 words, separator of #, and default word list + Star Trek and Star Wars. Saved as "Passphrase - Standard"
- Other has 4 words, separator of <blank>, Salt between each word, and default word list + Star Trek and Star Wars. Saved as "Passphrase - Salty"

Both (all) profiles using Diceware use the settings that were last shown from the configuration in the Options page (by clicking on the gear next to the custom algorithm dropdown), regardless of the intended settings. The Preview page shows this readily. The only way I could get the intended changes between profiles to "stick" was to open the gear and change the Diceware Password Generation Options page. The options page for Diceware will SHOW the settings from whatever profile is selected, but only the last thing saved is being used for all profiles, regardless of settings intended.

Recreation steps:
1. Open Password Generation Options.
1. Save default Diceware settings (gear icon) to profile1 in Settings tab.
2. Check Preview tab, confirm output matches.
2. Return to Settings tab and change Diceware settings (gear icon) to include ^& between words
3. Save to profile2 in Settings tab.
4. Check Preview tab, confirm output matches.
5. Return to Settings tab and select profile1 from dropdown in Settings tab.
6. Check preview tab, see profile2 values. :(
7. Return to Settings tab and change Diceware settings (gear icon) to change to ** between words.
8. Check Preview tab right away, output now has stars.
9. Return to Settings tab and select profile1 from dropdown in Settings tab.
6. Check preview tab, output has stars.
7. Return to Settings tab and select profile2 from dropdown in Settings tab.
6. Check preview tab, output has stars.

Right now, this means I can only save a single Profile option. :(

**Comment by nitz** [comment]
Hmm, yeah I see what you're saying. It's definitely "working as intended" the way it's written, because the plugin only supports a single set of options. It may be as simple as using the name of the active profile as part of the saved config "key" (the way the plugin looks up the settings that KeePass holds & stores for it). I'll look into it!

**Comment by nitz** [comment]
I just published `v1.2.0` that should use per-profile options! Let me know if you run into any issues with it!

**Comment by Truncated** [comment]
This has been working fine for me on multiple PCs for a while now. Thanks!
