### ISSUE TITLE
Not compatible with newest keepass? 

### ISSUE THREAD

**Issue by allopislozano** [cmdwtf/KeePassDiceware#35]
I'm getting an error when trying to use this plugin. Is it not compatible with latest version of keepass? 

![image](https://github.com/user-attachments/assets/0ac10b13-5412-4b04-bfa3-665d39603462)

Thanks

**Comment by nitz** [comment]
What version of KeePassDiceware do you have? I'm currently using it with KeePass v2.57.1 without issue.

**Comment by allopislozano** [comment]
I was using 2.56. After upgrading keepass to 2.57  now it works with keepassdiceware 2.0.0.

Thanks!

**Comment by ltguillaume** [comment]
Keepass 2.59 gives the same message for [v2.1.0](https://github.com/cmdwtf/KeePassDiceware/releases/tag/v2.1.0).

**Comment by nitz** [comment]
Hey Guillaume,

Would you mind opening a fresh issue and provide some more details about your setup if you're still having this issue? That said, a fresh KeePass install in a Windows sandbox doesn't reproduce the issue for me: 

<img width="1017" height="767" alt="Image" src="https://github.com/user-attachments/assets/75a3f075-871a-4a45-9267-1e4ab0a31c37" />

**Comment by ltguillaume** [comment]
Makes no sense, I tried it twice, nice dice (😉), but third time's - indeed, as it turns out -  the charm. The only thing I did was remove some old plugin cache items from `%LocalAppData%\KeePass\PluginCache`, don't think that changed anything.

Anyway, all's well now! Thanks!
