### ISSUE TITLE
Password Generation Options with Diceware not respecting Advanced tab entries

### ISSUE THREAD

**Issue by Truncated** [cmdwtf/KeePassDiceware#7]
Greetings again! :)

Problem:
When adding the following:
![Fields](https://user-images.githubusercontent.com/14208325/164944772-17dd44bf-beb0-4f73-9031-165d124392be.png)

`\/.,'";:~<>{}[]()`
to the Advanced--> Exclude the following characters: field, the Preview clearly shows some of the characters listed as being used.
![Preview with ignored values](https://user-images.githubusercontent.com/14208325/164944781-d8f8d097-3327-45a9-b06f-45215e8cb3e3.png)

Exclude look-alike characters checkbox is also ignored.

Use-Cases:
I tend to add brackets, slashes, dots, commas and quotes to the "Exclude the following characters" list to avoid the following scenarios:

- After having passwords essentially crash some coding on linux machines due to quotes or slashes being allowed in the UI but screwing up the programming calls.
- Exclude characters that are difficult or impossible to enter on specific interfaces, like TVs, Consoles, LCD-push-button-mini devices, etc.

Thanks!

**Comment by nitz** [comment]
Confirmed! I didn't even realize that tab existed 😂

I imagine KeePass exposes those to the plugin and that I'm just not taking them into account. Shouldn't be too hard to round up and fix.

**Comment by nitz** [comment]
Got this fixed and it will be released in the next version!
